In [6]:
!pip install PyMySQL
# https://github.com/PyMySQL/PyMySQL/

In [1]:
import pymysql.cursors
import warnings
import pandas as pd
warnings.filterwarnings('ignore')

In [4]:
def connect():
    # database credentials
    host = 'den1.mysql6.gear.host'
    db = 'situation'
    usr = 'situation'
    pwd = input()

    # connect to the database
    try: 
        return pymysql.connect(host=host, user=usr, password=pwd, database=db, 
            cursorclass=pymysql.cursors.DictCursor)
    except pymysql.Error as err:
        print("error %d: %s" %(err.args[0], err.args[1]))
        return ""

In [5]:
def get_tables(selected):
    # query all tables in database
    sql = "show tables;"
    retval = []

    # connect to database
    dbConnection = connect()

    # check for type, if not str proceed
    if not (type(dbConnection) == str):
        # execute query via cursor, fetch all data
        with dbConnection.cursor() as cursor:
          cursor.execute(sql)
          result = cursor.fetchall()

        # now try to find tables with parameter selected in name
        # and append to list
        for count in range(0, len(result)):
            for (key, value) in result[count].items():
                if (value.find(selected) != -1):
                    print(value)
                    retval.append(value)
    
    # return list
    return retval

In [6]:
def describe_table(myTable):
    sql = "describe " + myTable + ";"
    
    # connect to database
    dbConnection = connect()
    
    # check for type, if not str proceed
    if not (type(dbConnection) == str):
        # execute query via cursor, fetch all data
        with dbConnection.cursor() as cursor:
            cursor.execute(sql)
            result = cursor.fetchall()
        
        # now try to describe the table
        for count in range(0, len(result)):
            for (key, value) in result[count].items():
                print(key ,":", value, "; ", end="")
            print("")

In [9]:
tables = get_tables("f6")
print(tables)

for table in tables:
    describe_table(table)
    display(pd.read_sql("select * from " + table + ";", connect()))

f6_entity
f6_laboratorytasks
f6_les_workflow
f6_workflow_step_chemicals
f6_workflow_step_devices
['f6_entity', 'f6_laboratorytasks', 'f6_les_workflow', 'f6_workflow_step_chemicals', 'f6_workflow_step_devices']
Field : Step_ID ; Type : int(11) ; Null : NO ; Key : PRI ; Default : None ; Extra :  ;
Field : Workflow_ID ; Type : int(11) ; Null : YES ; Key : MUL ; Default : None ; Extra :  ;
Field : Unit_Operation_ID ; Type : int(11) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : Predecessor_ID ; Type : int(11) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : Successor_ID ; Type : int(11) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : step_name ; Type : varchar(255) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : description ; Type : varchar(255) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : step_param ; Type : varchar(255) ; Null : YES ; Key :  ; Default : None ; Extra :  ;

,Step_ID,Workflow_ID,Unit_Operation_ID,Predecessor_ID,Successor_ID,step_name,description,step_param
0,1,1,None,NaN,2.0,Safety Precautions,Put on appropriate PPE and ensure proper venti...,Safety parameters
1,2,1,None,1.0,3.0,Materials and Reagents,Gather necessary materials and reagents.,Materials parameters
2,3,1,None,2.0,4.0,Weighing and Mixing,Weigh and mix salicylic acid and acetic anhydr...,Weighing parameters
3,4,1,None,3.0,5.0,Reaction Setup,Place the flask in a water bath and add sulfur...,Reaction setup parameters
4,5,1,None,4.0,6.0,Heating and Reaction,Heat the mixture in the water bath.,Heating parameters
5,6,1,None,5.0,7.0,Cooling and Crystallization,Allow the flask to cool and add distilled water.,Cooling parameters
6,7,1,None,6.0,8.0,Filtration,Set up a Buchner funnel for filtration.,Filtration parameters
7,8,1,None,7.0,9.0,Washing and Drying,Wash and dry the aspirin crystals.,Washing parameters
8,9,1,None,8.0,10.0,Data Collection,"Record mass and appearance, calculate yield.",Data collection parameters
9,10,1,None,9.0,11.0,Characterization,Use techniques for identity and purity confirm...,Characterization parameters
10,11,1,None,10.0,12.0,Cleanup,Dispose of waste and clean equipment.,Cleanup parameters
11,12,1,None,11.0,13.0,Documentation,Record all data in a notebook or report.,Documentation parameters
12,13,1,None,12.0,14.0,Safety and Waste Disposal,Dispose of chemicals and waste properly.,Safety and waste disposal parameters
13,14,1,None,13.0,NaN,Analysis and Discussion,Analyze results and discuss synthesis success.,Analysis and discussion parameters
14,15,2,None,NaN,16.0,Safety Precautions,Wear appropriate PPE and ensure proper ventila...,Safety parameters
15,16,2,None,15.0,17.0,Materials and Reagents,Gather necessary materials and reagents.,Materials parameters
16,17,2,None,16.0,18.0,Weighing and Mixing,Weigh and mix copper oxide and sulfuric acid.,Weighing parameters
17,18,2,None,17.0,19.0,Reaction Setup,Place the beaker on a stirring hot plate.,Reaction setup parameters
18,19,2,None,18.0,20.0,Heating and Reaction,Heat the mixture while stirring.,Heating parameters
19,20,2,None,19.0,21.0,Cooling and Precipitation,Let the mixture cool to room temperature.,Cooling parameters
20,21,2,None,20.0,22.0,Filtration,Set up a vacuum filtration system.,Filtration parameters
21,22,2,None,21.0,23.0,Washing and Drying,Wash and dry the copper sulfate pentahydrate c...,Washing parameters
22,23,2,None,22.0,24.0,Data Collection,"Record mass and appearance, calculate yield.",Data collection parameters
23,24,2,None,23.0,25.0,Characterization,Use techniques for identity and purity confirm...,Characterization parameters
24,25,2,None,24.0,26.0,Cleanup,Dispose of waste and clean equipment.,Cleanup parameters
25,26,2,None,25.0,27.0,Documentation,Record all data in a notebook or report.,Documentation parameters
26,27,2,None,26.0,28.0,Safety and Waste Disposal,Dispose of chemicals and waste properly.,Safety and waste disposal parameters
27,28,2,None,27.0,NaN,Analysis and Discussion,Analyze results and discuss synthesis success.,Analysis and discussion parameters

Field : TaskID ; Type : int(11) ; Null : NO ; Key : PRI ; Default : None ; Extra : auto_increment ;
Field : TaskStatus ; Type : enum('pending','in-progress','completed') ; Null : NO ; Key :  ; Default : None ; Extra :  ;
Field : ResourceAllocated ; Type : varchar(255) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : TimeSpent ; Type : decimal(5,2) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : Reward ; Type : decimal(5,2) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : Timestamp ; Type : timestamp ; Null : NO ; Key :  ; Default : CURRENT_TIMESTAMP ; Extra : on update CURRENT_TIMESTAMP ;

,TaskID,TaskStatus,ResourceAllocated,TimeSpent,Reward,Timestamp
0,1,pending,Resource1,0.0,0.0,2024-05-12 08:28:45
1,2,in-progress,Resource2,1.5,0.5,2024-05-12 08:28:48
2,3,completed,Resource3,2.0,1.0,2024-05-12 08:28:50
3,4,pending,Resource4,2.5,1.5,2024-05-12 08:28:52
4,5,in-progress,Resource5,3.0,2.0,2024-05-12 08:28:54
5,6,completed,Resource1,0.0,0.0,2024-05-12 08:28:56
6,7,pending,Resource2,1.5,0.5,2024-05-12 08:28:58
7,8,in-progress,Resource3,2.0,1.0,2024-05-12 08:29:01
8,9,completed,Resource4,2.5,1.5,2024-05-12 08:29:03
9,10,pending,Resource5,3.0,2.0,2024-05-12 08:29:05
10,11,in-progress,Resource1,0.0,0.0,2024-05-12 08:29:07
11,12,completed,Resource2,1.5,0.5,2024-05-12 08:29:10
12,13,pending,Resource3,2.0,1.0,2024-05-12 08:29:12
13,14,in-progress,Resource4,2.5,1.5,2024-05-12 08:29:14
14,15,completed,Resource5,3.0,2.0,2024-05-12 08:29:16
15,16,pending,Resource1,0.0,0.0,2024-05-12 08:29:18
16,17,in-progress,Resource2,1.5,0.5,2024-05-12 08:29:20
17,18,completed,Resource3,2.0,1.0,2024-05-12 08:29:22
18,19,pending,Resource4,2.5,1.5,2024-05-12 08:29:23
19,20,in-progress,Resource5,3.0,2.0,2024-05-12 08:29:25
20,21,completed,Resource1,0.0,0.0,2024-05-12 08:29:27
21,22,pending,Resource2,1.5,0.5,2024-05-12 08:29:29
22,23,in-progress,Resource3,2.0,1.0,2024-05-12 08:29:31
23,24,completed,Resource4,2.5,1.5,2024-05-12 08:29:33
24,25,pending,Resource5,3.0,2.0,2024-05-12 08:29:35
25,26,in-progress,Resource1,0.0,0.0,2024-05-12 08:29:37
26,27,completed,Resource2,1.5,0.5,2024-05-12 08:29:39
27,28,pending,Resource3,2.0,1.0,2024-05-12 08:29:41
28,29,in-progress,Resource4,2.5,1.5,2024-05-12 08:29:44
29,30,completed,Resource5,3.0,2.0,2024-05-12 08:29:46
30,31,pending,Resource1,0.0,0.0,2024-05-12 08:29:48
31,32,in-progress,Resource2,1.5,0.5,2024-05-12 08:29:50
32,33,completed,Resource3,2.0,1.0,2024-05-12 08:29:53
33,34,pending,Resource4,2.5,1.5,2024-05-12 08:29:55
34,35,in-progress,Resource5,3.0,2.0,2024-05-12 08:29:57
35,36,completed,Resource1,0.0,0.0,2024-05-12 08:30:00
36,37,pending,Resource2,1.5,0.5,2024-05-12 08:30:02
37,38,in-progress,Resource3,2.0,1.0,2024-05-12 08:30:04
38,39,completed,Resource4,2.5,1.5,2024-05-12 08:30:07

Field : Workflow_ID ; Type : int(11) ; Null : NO ; Key : PRI ; Default : None ; Extra :  ;
Field : Workflow_Name ; Type : varchar(255) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : Description ; Type : varchar(255) ; Null : YES ; Key :  ; Default : None ; Extra :  ;

,Workflow_ID,Workflow_Name,Description
0,1,Aspirin Synthesis,Aspirin synthesis workflow description
1,2,Copper Sulfate Pentahydrate Synthesis,Copper sulfate pentahydrate synthesis workflow...

Field : Workflow_Chemicals_ID ; Type : int(11) ; Null : NO ; Key : PRI ; Default : None ; Extra :  ;
Field : Chemical_ID ; Type : int(11) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : Step_ID ; Type : int(11) ; Null : YES ; Key : MUL ; Default : None ; Extra :  ;
Field : Predecessor_ID ; Type : int(11) ; Null : YES ; Key : MUL ; Default : None ; Extra :  ;
Field : Successor_ID ; Type : int(11) ; Null : YES ; Key : MUL ; Default : None ; Extra :  ;
Field : amount ; Type : varchar(255) ; Null : YES ; Key :  ; Default : None ; Extra :  ;

,Workflow_Chemicals_ID,Chemical_ID,Step_ID,Predecessor_ID,Successor_ID,amount
0,1,101,3,None,None,10 grams
1,2,102,3,None,None,5 grams
2,3,103,3,None,None,2 grams
3,4,104,4,None,None,15 mL
4,5,105,5,None,None,N/A
5,6,106,6,None,None,50 mL
6,7,107,6,None,None,100 mL
7,8,108,7,None,None,N/A
8,9,109,8,None,None,N/A
9,10,110,9,None,None,20 mL
10,11,111,9,None,None,50 mL
11,12,112,9,None,None,N/A
12,13,113,10,None,None,N/A
13,14,114,11,None,None,N/A

Field : Workflow_Devices_ID ; Type : int(11) ; Null : NO ; Key : PRI ; Default : None ; Extra :  ;
Field : Device_ID ; Type : int(11) ; Null : YES ; Key :  ; Default : None ; Extra :  ;
Field : Step_ID ; Type : int(11) ; Null : YES ; Key : MUL ; Default : None ; Extra :  ;
Field : Predecessor_ID ; Type : int(11) ; Null : YES ; Key : MUL ; Default : None ; Extra :  ;
Field : Successor_ID ; Type : int(11) ; Null : YES ; Key : MUL ; Default : None ; Extra :  ;

    Workflow_Devices_ID  Device_ID  Step_ID Predecessor_ID Successor_ID
0                     1        201        4           None         None
1                     2        202        5           None         None
2                     3        203        5           None         None
3                     4        204        7           None         None
4                     5        205        9           None         None
5                     6        206       10           None         None
6                     7        207       12           None         None
7                     8        208       13           None         None
8                     9        209       14           None         None
9                    10        210       14           None         None
10                   11        211       14           None         None
11                   12        212       14           None         None
12                   13        213       14           None         None
13                   14        214       14           None         None